# This file is designed for production server deployment, not local development work
# For a containerized local dev environment, see: https://github.com/mastodon/mastodon/blob/main/README.md#docker

services:
  web:
    image: ghcr.io/sleepdeprecation/mastodon
    restart: always
    env_file: env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --header 'x-forwarded-proto: https' --proxy=off localhost:3000/api/v1/instance || exit 1"]
    ports:
      - "3000:3000"
    volumes:
      - /opt/masto/public/system:/mastodon/public/system

  streaming:
    image: ghcr.io/sleepdeprecation/mastodon-streaming
    restart: always
    env_file: env.production
    command: node ./streaming/index.js
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --header 'x-forwarded-proto: https' --proxy=off localhost:4000/api/v1/streaming/health || exit
1"]
    ports:
      - "4000:4000"

  sidekiq:
    image: ghcr.io/sleepdeprecation/mastodon
    restart: always
    env_file: env.production
    environment:
      DB_POOL: 7
    command: bundle exec sidekiq -c 7
    networks:
      - external_network
      - internal_network
    volumes:
      - /opt/masto/public/system:/mastodon/public/system
    deploy:
      mode: replicated
      replicas: 2

networks:
  external_network:
    internal: false
  internal_network:
    internal: true

